Content:
  isopod_examples:
    root_dir: ${ROOT_DIR}/examples
  isopod:
    root_dir: ${ROOT_DIR}/doc/content
  framework:
    root_dir: ${MOOSE_DIR}/framework/doc/content
  heat_transfer:
    root_dir: ${MOOSE_DIR}/modules/heat_transfer/doc/content
  ray_tracing:
    root_dir: ${MOOSE_DIR}/modules/ray_tracing/doc/content
  solid_mechanics:
    root_dir: ${MOOSE_DIR}/modules/solid_mechanics/doc/content
  optimization:
    root_dir: ${MOOSE_DIR}/modules/optimization/doc/content
  modules:
    root_dir: ${MOOSE_DIR}/modules/doc/content
    content:
      - help/development/analyze_jacobian.md

Renderer:
  type: MooseDocs.base.MaterializeRenderer

Extensions:
  MooseDocs.extensions.navigation:
    name: Isopod
    repo: https://github.com/idaholab/isopod
    menu:
      Examples: examples/index.md
      Syntax: syntax/index.md

  MooseDocs.extensions.appsyntax:
    executable: ${ROOT_DIR}
    remove:
      framework: !include ${MOOSE_DIR}/framework/doc/remove.yml

  MooseDocs.extensions.common:
    shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml

  MooseDocs.extensions.acronym:
    acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml

  MooseDocs.extensions.template:
        active: True
  MooseDocs.extensions.sqa:
      active: False
      reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
      repos:
          default: https://github.com/idaholab/isopod
          moose: https://github.com/idaholab/moose
      categories:
          framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
          heat_transfer: !include ${MOOSE_DIR}/modules/heat_transfer/doc/sqa_heat_transfer.yml
          solid_mechanics: !include ${MOOSE_DIR}/modules/solid_mechanics/doc/sqa_solid_mechanics.yml
          optimization: !include ${MOOSE_DIR}/modules/optimization/doc/sqa_optimization.yml
          isopod: !include ${ROOT_DIR}/doc/sqa_isopod.yml
  MooseDocs.extensions.bibtex:
      duplicates:
          - hales15homogenization

  MooseDocs.extensions.algorithm:
      active: True
